"""Write the controlled-vocabulary concepts a scenario's catalog records use, as one Turtle file.

SHACL checks code-list membership (skos:inScheme) and the class of a value
against the data graph, so the validator needs the concepts the records point
at. Rather than ship whole authority tables, this fetches only those concepts
from their publishers and keeps what validation reads: type, scheme and English
label, plus the scheme's title. Each concept is also given the class the
profile's range shapes expect for the property that uses it (dct:Frequency,
dct:LicenseDocument, ...), which the publishers' own data leaves to inference.

Run it inside the validator image, which has rdflib:

    IMG=europe-west4-docker.pkg.dev/sacred-sol-99413/sth-public/shacl-validator:87c963c0
    DIR=backend/scenarios/catalog-profiles/mobilitydcat-ap-3.0.0
    docker run --rm -v "$PWD":/w --entrypoint sh $IMG -c "cd /app && poetry run python \\
        /w/scripts/vocabulary-subset.py /w/backend/scenarios/fuse4ccam.json /w/$DIR/*shapes.ttl /w/$DIR/*range*.ttl" \\
        > $DIR/vocabulary-subset.ttl
"""
import json
import sys
import urllib.request

from rdflib import Graph, Literal, URIRef
from rdflib.namespace import DCTERMS, RDF, SKOS

PREFIXES = {
    'dcat': 'http://www.w3.org/ns/dcat#',
    'dct': 'http://purl.org/dc/terms/',
    'mobilitydcatap': 'https://w3id.org/mobilitydcat-ap#',
}
VOCABULARIES = ('https://w3id.org/mobilitydcat-ap/', 'http://publications.europa.eu/resource/authority/')
SH = 'http://www.w3.org/ns/shacl#'

scenario_file, *shape_files = sys.argv[1:]
expand = lambda term: PREFIXES[term.split(':', 1)[0]] + term.split(':', 1)[1] if term.split(':', 1)[0] in PREFIXES else term


def uses(record):
    for path, values in record.items():
        for v in values:
            if 'iri' in v and v['iri'].startswith(VOCABULARIES):
                yield URIRef(expand(path)), URIRef(v['iri'])
            if 'fields' in v:
                yield from uses(v['fields'])


scenario = json.load(open(scenario_file))
used = {}
for asset in scenario['assets']:
    for p, concept in uses(asset.get('dcatFields', {}).get('record', {})):
        used.setdefault(concept, set()).add(p)

shapes = Graph()
for f in shape_files:
    shapes.parse(f, format='turtle')
ranges = {}
for prop in shapes.subjects(URIRef(SH + 'class'), None):
    for p in shapes.objects(prop, URIRef(SH + 'path')):
        ranges.setdefault(p, set()).update(o for o in shapes.objects(prop, URIRef(SH + 'class')) if isinstance(o, URIRef))


def fetch(iri, attempts=3):
    # The EU tables answer reliably in RDF/XML only; w3id redirects to Turtle.
    accept = 'application/rdf+xml' if 'publications.europa.eu' in str(iri) else 'text/turtle'
    for attempt in range(attempts):
        try:
            req = urllib.request.Request(str(iri), headers={'Accept': accept})
            with urllib.request.urlopen(req, timeout=60) as r:
                body, ctype = r.read(), r.headers.get('Content-Type', '')
            return Graph().parse(data=body, format='turtle' if 'turtle' in ctype else 'xml')
        except Exception:
            if attempt == attempts - 1:
                raise


english = lambda labels: next((l for l in labels if isinstance(l, Literal) and l.language in ('en', None)), None)
out = Graph()
out.bind('skos', SKOS)
out.bind('dct', DCTERMS)
schemes = set()
for concept in sorted(used):
    source = fetch(concept)
    # Only the scheme the concept's IRI sits in; EU tables also list sub-collections there.
    scheme = URIRef(str(concept).rsplit('/', 1)[0])
    if (concept, SKOS.inScheme, scheme) not in source:
        sys.exit(f'{concept} is not in {scheme}')
    out.add((concept, SKOS.inScheme, scheme))
    for t in source.objects(concept, RDF.type):
        out.add((concept, RDF.type, t))
    for p in used[concept]:
        for t in ranges.get(p, ()):
            out.add((concept, RDF.type, t))
    label = english(source.objects(concept, SKOS.prefLabel))
    if label:
        out.add((concept, SKOS.prefLabel, Literal(str(label), lang='en')))
    schemes.add(scheme)

for scheme in sorted(schemes):
    source = fetch(scheme)
    title = english(list(source.objects(scheme, DCTERMS.title)) + list(source.objects(scheme, SKOS.prefLabel)))
    out.add((scheme, RDF.type, SKOS.ConceptScheme))
    out.add((scheme, DCTERMS.title, Literal(str(title) if title else str(scheme).rsplit('/', 1)[-1], lang='en')))

header = f"""# Controlled-vocabulary concepts used by the {scenario['name']} scenario's catalog records.
# Generated by scripts/vocabulary-subset.py; regenerate rather than edit.
#
# Sources: mobilityDCAT-AP controlled vocabularies (https://w3id.org/mobilitydcat-ap/, CC BY 4.0)
# and EU Vocabularies authority tables (http://publications.europa.eu/resource/authority/,
# (c) European Union, reuse under CC BY 4.0). The rdf:type of a profile's range class is added here.

"""
sys.stdout.write(header + out.serialize(format='turtle'))
print(f'{len(used)} concepts in {len(schemes)} schemes', file=sys.stderr)
